### ISSUE TITLE
As a dev, I need an environment

### ISSUE THREAD

**Issue by HandsfreeDashboard** [HandsfreeDashboard/dashboard#1]
## About
Let's build a [Vue](https://vuejs.org/) front end and use [Firebase](https://firebase.google.com/) for our backend. The benefits to this are:
* Very fast development cycle
  * 100% HTML5 (and Node)
  * Uses the Google stack
* Easy adoption
  * Very low system requirements
  * Easy to fork and deploy

## Environment
* [ ]  Install Vuetify
* [ ]  Change basic branding (title, favicon)
* [ ]  Create an ultra lightweight splash screen that loads before even Vuetify does...goal is to have it load instantly

Let's give readers a reason to read, try the demos, and join the movement 🎉

## Loading Screen
I'm thinking: dramatically change the background on each loading step. Once everything's loaded shoot some fireworks. Make it really spectacular and worth the loading wait (which won't be there next time due to cache!)

* https://codepen.io/juliangarnier/pen/gmOwJX - Fireworks
* https://codepen.io/alexzaworski/pen/mEkvAG - Background change with fireworks
* https://codepen.io/tomrishworth/pen/VbbMgV - Anime with VueJS

Loading steps will including:

* [ ]  Loading anime/vuetify
* [ ]  Loading handsfree.js
* [ ]  Loading landing page content

### Tasks
* [ ]  Make nicer No-Script message
* [x]  Create SVG version of logo
* [ ]  Include anime.js
* [ ]  Include handsfree.js

> ...more sooon
